import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'app.dart';

void main() async {
  // REQUIRED: Ensure Flutter engine is initialized before calling native code
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the settings generated by FlutterFire CLI
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const BlockitApp());
}
